version: "3.9"
services:
  backend:
    build:
      context: backend
      target: development
    command: npm run start:debug
    ports:
      - 8080:3000
      - 9229:9229
    volumes:
      - ./backend/:/usr/src/app:delegated
      - /usr/src/app/node_modules
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    env_file:
      - .env
